### PR TITLE
Support for responsive forms

### PR DESCRIPTION
**Pull request by dermarkus**
As requested in issue #3

### CODE REVIEW

**Comment by antage** [comment]
Thanks for the patch. I'll review it today or tomorrow.

**Comment by antage** [comment]
Good work! But I noticed a few of glithes:

Unaligned field

Label text should be in the same line with input

Default sized input shouldn't have width greater 300px

Could you correct styles to fix these issues?

And I think `responsive.scss` should be `responsive.css.scss`.

**Comment by antage** [comment]
Thanks! I've merged your patch in develop branch. I want to play with styles before I release it.

**Comment by stonehz** [comment]
+1
Let us know when we can give it a try

**Pull request merged**
